USE ADMINPT
GO

/*
DROP TABLE DIFERENCIAS_ALMAPAC

CREATE TABLE DIFERENCIAS_ALMAPAC(
	ID_DIF_ALMA INT,
	ID_ES_ENCA INT,
	FECHA_ALMA DATETIME,
	NUM_DOC_ALMA VARCHAR(100),
	TM_JIBOA NUMERIC(20,4),
	TM_ALMA NUMERIC(20,4),
	TM_DIF_ALMA NUMERIC(20,4),
	TM_DIF_JIBOA NUMERIC(20,4),
	USUARIO_CREA VARCHAR(100),
	FECHA_CREA DATETIME,
	CONSTRAINT PK_ENTRADA_SALIDA_ALMA PRIMARY KEY (ID_DIF_ALMA),
	CONSTRAINT FK_ENTRADA_SALIDA_ALMA01 FOREIGN KEY(ID_ES_ENCA) REFERENCES ENTRADA_SALIDA_ENCA (ID_ES_ENCA)
)

CREATE TABLE ENTRA_SALIDA_COMP(
	ID_ES_COMP INT,
	ID_ES_ENCA INT,
	FAC_NUM VARCHAR(100),
	FAC_FECHA DATETIME,
	VAPOR VARCHAR(100),
	USUARIO_CREA VARCHAR(100),	
	FECHA_CREA DATETIME,
	CONSTRAINT PK_ENTRA_SALIDA_COMP PRIMARY KEY (ID_ES_COMP),
	CONSTRAINT FK_ENTRA_SALIDA_COMP01 FOREIGN KEY(ID_ES_ENCA) REFERENCES ENTRADA_SALIDA_ENCA (ID_ES_ENCA)
)
*/
/*
	************************************************************************************************************************
										IMPORTACION DE CARGA AZUCAR CRUDA ARCHIVO ALMAPAC
	************************************************************************************************************************
*/

-- Traslados por Notas de remisión de Azúcar Cruda *********************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
	E.FECHA, 
	E.NUM_DOC,
	E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
	E.ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	E.ID_ORDEN_TRAS,
	E.ID_PROV_TRAS,
	E.ID_TRANSPORTE,
	E.MOTORISTA,
	E.NIT,
	E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
	E.FECHADESPACHO,
	1 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
	E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
	E.OBSERVACION_RGTRASLADO,
	E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
	E.MNOTAABONO
FROM ENTRADA_SALIDA_ENCA E
WHERE E.ID_BODEP = 29 -- JIBOA (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND (SELECT COUNT(1) FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA AND D.ID_PRODUCTO = 2) > 0 -- AZUCAR CRUDA
AND (SELECT COUNT(1) FROM CRUDA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN CRUDA$

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT T.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA  T WHERE T.PARENT_ID = E.ID_ES_ENCA AND USUARIO_CREA = 'DBO_ADMINPT_CRUDA') AS ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM CRUDA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, D.QUINTALES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) *1000 FROM CRUDA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS KILOGRAMOS, D.GALONES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM CRUDA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND E.ID_BODEP = 29 -- JIBOA (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND (SELECT COUNT(1) FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA AND D.ID_PRODUCTO = 2) > 0 -- AZUCAR CRUDA
AND (SELECT COUNT(1) FROM CRUDA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN CRUDA$

-- Registro de diferencias en Azúcar Cruda ************************************************************************************************************************
INSERT DIFERENCIAS_ALMAPAC
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_DIF_ALMA),0) FROM DIFERENCIAS_ALMAPAC D) AS ID_DIF_ALMA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 17 AND E.ID_BODEGAO = 29 AND E.ID_BODEGAD = 17) AS ID_ES_ENCA,
	C.FECHA_ALMAPAC AS FECHA_ALMA, C.DOCUM_ALMAPAC AS NUM_DOC_ALMA, CAST(C.TM_JIBOA_ALMAPAC AS NUMERIC(20,4)) AS TM_JIBOA, CAST(C.TM_ALMAPAC AS NUMERIC(20,4)) AS TM_ALMA, 
	(CAST(C.TM_ALMAPAC AS NUMERIC(20,4)) - CAST(C.TM_JIBOA_ALMAPAC AS NUMERIC(20,4))) AS TM_DIF_ALMA, 0 AS TM_DIF_JIBOA,
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA
FROM CRUDA$ C

-- Ajuste por diferencias en Azúcar Cruda ************************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ID_ES_ENCA, PARENT_ID, COD_CAPTURA, FECHA, NUM_DOC, NUM_DOC_PESOS, ES_PROPIO, ES_AJENO, ID_ZAFRA_PROD, ID_ZAFRA_ACTUAL,
	IIF( DIFERENCIA_ALMAPAC > 0, 1, 2) AS ID_TIPO_MOV, IIF( DIFERENCIA_ALMAPAC > 0, 6, 7) AS ID_CONCE, IIF( DIFERENCIA_ALMAPAC > 0, 45, 41) AS ID_ESPECI,
	ID_BODEGAO, ID_BODEGAD,
	USUARIO_CREA, FECHA_CREA, USUARIO_ACT, FECHA_ACT,
	ID_ESTADO, ID_ORDEN_TRAS, ID_PROV_TRAS, ID_TRANSPORTE, MOTORISTA, NIT, 
	PLACA_CABEZAL, PLACA_REMOLQUE, CONTENEDOR, MARCHAMOS, CAST(DIFERENCIA_ALMAPAC AS VARCHAR(100)) AS OBSERVACION, NFORMULARIO,
	ENCCLIENTE, ENCNIT, ENCNRC, ENCDEPARTAMENTO, ENCMUNICIPIO, ENCGIRO, ENCDIRECCION, 
	FECHADESPACHO,
	ID_TIPO, ID_BODEP, ID_FMPAGO, EFECTIVO, CHEQUE, NOTAABONO, TOTAL, NCUENTA, NCHEQUE,
	BANCO, ID_ESTIBA, TENDIDO, FECHA_PRODUCCION, COLOR, FECHA_PRODUCCION1, 
	OBSERVACION_RGTRASLADO,
	FECHA_RGTRASLADO, NUM_DOC_ALMPAC, ID_CLIENTEEXP, ID_CLIENTEING, DONACION, MCHEQUE,
	MNOTAABONO
FROM (
	SELECT  -- Notas de remisión ingresadas en bodega principal de ALMAPAC
		ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
		E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
		E.FECHA, 
		ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS NUM_DOC,
		E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
		10 AS ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
		--2 AS ID_TIPO_MOV, 19 AS ID_CONCE, 46 AS ID_ESPECI, 
		17 AS ID_BODEGAO, 17 AS ID_BODEGAD,
		(		
			ISNULL((SELECT SUM(F.TM_ALMA) FROM DIFERENCIAS_ALMAPAC F WHERE F.ID_ES_ENCA = E.ID_ES_ENCA), 0) -
			ISNULL((SELECT D.TM FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA) , 0 )
		) AS DIFERENCIA_ALMAPAC,
		'DBO_ADMINPT_CRUDA_DIF' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA_DIF' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
		11 AS ID_ESTADO, 
		E.ID_ORDEN_TRAS,
		E.ID_PROV_TRAS,
		E.ID_TRANSPORTE,
		E.MOTORISTA,
		E.NIT,
		E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
		E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
		E.FECHADESPACHO,
		5 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
		E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
		E.OBSERVACION_RGTRASLADO,
		E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
		E.MNOTAABONO
	FROM ENTRADA_SALIDA_ENCA E
	WHERE E.ID_BODEP = 17 -- ALMAPAC (P)
	AND E.ID_BODEGAO = 29 -- JIBOA
	AND E.ID_BODEGAD = 17 -- ALMAPAC
	AND E.ID_TIPO_MOV = 1 -- ENTRADAS
	AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
	AND E.USUARIO_CREA = 'DBO_ADMINPT_CRUDA'
) X
WHERE DIFERENCIA_ALMAPAC <> 0

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	E.ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, D.ID_UNIDAD_FAC, ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) AS CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_CRUDA_DIF' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA_DIF' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) * (100 / 2.174) AS QUINTALES, 
	ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) * 1000 AS KILOGRAMOS, D.GALONES, 
	ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.PARENT_ID = D.ID_ES_ENCA
AND E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 17 -- ALMAPAC
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.USUARIO_CREA = 'DBO_ADMINPT_CRUDA_DIF'



/*
	************************************************************************************************************************
											IMPORTACION DE MELAZA ARCHIVO ALMAPAC
	************************************************************************************************************************
*/
-- Traslados por Notas de remisión de Melaza *********************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
	E.FECHA, 
	E.NUM_DOC,
	E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
	E.ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	E.ID_ORDEN_TRAS,
	E.ID_PROV_TRAS,
	E.ID_TRANSPORTE,
	E.MOTORISTA,
	E.NIT,
	E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
	E.FECHADESPACHO,
	1 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
	E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
	E.OBSERVACION_RGTRASLADO,
	E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
	E.MNOTAABONO
FROM ENTRADA_SALIDA_ENCA E
WHERE E.ID_BODEP = 29 -- JIBOA (P) 
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND (SELECT COUNT(1) FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA AND D.ID_PRODUCTO = 5) > 0 -- MELAZA
AND (SELECT COUNT(1) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN MELAZA$

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT T.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA  T WHERE T.PARENT_ID = E.ID_ES_ENCA AND USUARIO_CREA = 'DBO_ADMINPT_MELAZA') AS ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, D.QUINTALES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC)*1000 FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS KILOGRAMOS, D.GALONES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND E.ID_BODEP = 29 -- JIBOA (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND D.ID_PRODUCTO = 5 -- MELAZA A GRANEL
AND (SELECT COUNT(1) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN MELAZA$

-- Registro de diferencias en Melaza cruda *********************************************************************************************************************
INSERT DIFERENCIAS_ALMAPAC
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_DIF_ALMA),0) FROM DIFERENCIAS_ALMAPAC D) AS ID_DIF_ALMA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 17 AND E.ID_BODEGAO = 29 AND E.ID_BODEGAD = 17) AS ID_ES_ENCA,
	C.FECHA_ALMAPAC AS FECHA_ALMA, C.DOCUM_ALMAPAC AS NUM_DOC_ALMA, CAST(C.TM_JIBOA_ALMAPAC AS NUMERIC(20,4)) AS TM_JIBOA, CAST(C.TM_ALMAPAC AS NUMERIC(20,4)) AS TM_ALMA, 
	(CAST(C.TM_ALMAPAC AS NUMERIC(20,4)) - CAST(C.TM_JIBOA_ALMAPAC AS NUMERIC(20,4))) AS TM_DIF_ALMA, 0 AS TM_DIF_JIBOA,
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA
FROM MELAZA$ C

-- Reconversion de Melaza: Salida *********************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
	E.FECHA, 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS NUM_DOC,
	E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
	E.ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
	2 AS ID_TIPO_MOV, 19 AS ID_CONCE, 46 AS ID_ESPECI, 17 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	E.ID_ORDEN_TRAS,
	E.ID_PROV_TRAS,
	E.ID_TRANSPORTE,
	E.MOTORISTA,
	E.NIT,
	E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
	E.FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
	E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
	E.OBSERVACION_RGTRASLADO,
	E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
	E.MNOTAABONO
FROM ENTRADA_SALIDA_ENCA E
WHERE E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 1 -- ENTRADAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.ID_ZAFRA_PROD <> 10 -- ZAFRAS ANTERIORES
AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA'

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT T.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA  T WHERE T.PARENT_ID = E.ID_ES_ENCA AND USUARIO_CREA = 'DBO_ADMINPT_MELAZA_RECONV') AS ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, D.ID_UNIDAD_FAC, D.CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, D.QUINTALES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC)*1000 FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS KILOGRAMOS, D.GALONES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 1 -- ENTRADAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.ID_ZAFRA_PROD <> 10 -- ZAFRA 22/23
AND D.ID_PRODUCTO = 5 -- MELAZA A GRANEL
AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA'

-- Reconversion de Melaza: Entrada *********************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
	E.FECHA, 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS NUM_DOC,
	E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
	10 AS ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 20 AS ID_CONCE, 47 AS ID_ESPECI, 17 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	E.ID_ORDEN_TRAS,
	E.ID_PROV_TRAS,
	E.ID_TRANSPORTE,
	E.MOTORISTA,
	E.NIT,
	E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
	E.FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
	E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
	E.OBSERVACION_RGTRASLADO,
	E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
	E.MNOTAABONO
FROM ENTRADA_SALIDA_ENCA E
WHERE E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 1 -- ENTRADAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.ID_ZAFRA_PROD <> 10 -- ZAFRAS ANTERIORES
AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA'

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT T.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA  T WHERE T.PARENT_ID = E.ID_ES_ENCA AND T.USUARIO_CREA = 'DBO_ADMINPT_MELAZA_RECONV' AND T.ID_TIPO_MOV = 1) AS ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, D.ID_UNIDAD_FAC, D.CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_RECONV' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, D.QUINTALES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC)*1000 FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS KILOGRAMOS, D.GALONES, 
	(SELECT SUM(C.TM_JIBOA_ALMAPAC) FROM MELAZA$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 1 -- ENTRADAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.ID_ZAFRA_PROD <> 10 -- ZAFRA 22/23
AND D.ID_PRODUCTO = 5 -- MELAZA A GRANEL
AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA'

-- Ajuste por diferencias en Melaza *********************************************************************************************************************
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ID_ES_ENCA, PARENT_ID, COD_CAPTURA, FECHA, NUM_DOC, NUM_DOC_PESOS, ES_PROPIO, ES_AJENO, ID_ZAFRA_PROD, ID_ZAFRA_ACTUAL,
	IIF( DIFERENCIA_ALMAPAC > 0, 1, 2) AS ID_TIPO_MOV, IIF( DIFERENCIA_ALMAPAC > 0, 6, 7) AS ID_CONCE, IIF( DIFERENCIA_ALMAPAC > 0, 45, 41) AS ID_ESPECI,
	ID_BODEGAO, ID_BODEGAD,
	USUARIO_CREA, FECHA_CREA, USUARIO_ACT, FECHA_ACT,
	ID_ESTADO, ID_ORDEN_TRAS, ID_PROV_TRAS, ID_TRANSPORTE, MOTORISTA, NIT, 
	PLACA_CABEZAL, PLACA_REMOLQUE, CONTENEDOR, MARCHAMOS, CAST(DIFERENCIA_ALMAPAC AS VARCHAR(100)) AS OBSERVACION, NFORMULARIO,
	ENCCLIENTE, ENCNIT, ENCNRC, ENCDEPARTAMENTO, ENCMUNICIPIO, ENCGIRO, ENCDIRECCION, 
	FECHADESPACHO,
	ID_TIPO, ID_BODEP, ID_FMPAGO, EFECTIVO, CHEQUE, NOTAABONO, TOTAL, NCUENTA, NCHEQUE,
	BANCO, ID_ESTIBA, TENDIDO, FECHA_PRODUCCION, COLOR, FECHA_PRODUCCION1, 
	OBSERVACION_RGTRASLADO,
	FECHA_RGTRASLADO, NUM_DOC_ALMPAC, ID_CLIENTEEXP, ID_CLIENTEING, DONACION, MCHEQUE,
	MNOTAABONO
FROM (
	SELECT  -- Notas de remisión ingresadas en bodega principal de ALMAPAC
		ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
		E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
		E.FECHA, 
		ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS NUM_DOC,
		E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
		10 AS ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
		--2 AS ID_TIPO_MOV, 19 AS ID_CONCE, 46 AS ID_ESPECI, 
		17 AS ID_BODEGAO, 17 AS ID_BODEGAD,
		(		
			ISNULL((SELECT SUM(F.TM_ALMA) FROM DIFERENCIAS_ALMAPAC F WHERE F.ID_ES_ENCA = E.ID_ES_ENCA), 0) -
			ISNULL((SELECT D.TM FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA) , 0 )
		) AS DIFERENCIA_ALMAPAC,
		'DBO_ADMINPT_MELAZA_DIF' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_DIF' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
		11 AS ID_ESTADO, 
		E.ID_ORDEN_TRAS,
		E.ID_PROV_TRAS,
		E.ID_TRANSPORTE,
		E.MOTORISTA,
		E.NIT,
		E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
		E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
		E.FECHADESPACHO,
		5 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
		E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
		E.OBSERVACION_RGTRASLADO,
		E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
		E.MNOTAABONO
	FROM ENTRADA_SALIDA_ENCA E
	WHERE E.ID_BODEP = 17 -- ALMAPAC (P)
	AND E.ID_BODEGAO = 29 -- JIBOA
	AND E.ID_BODEGAD = 17 -- ALMAPAC
	AND E.ID_TIPO_MOV = 1 -- ENTRADAS
	AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
	AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA'
) X
WHERE DIFERENCIA_ALMAPAC <> 0

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	E.ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, D.ID_UNIDAD_FAC, CAST( ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) * (100 / 2.174) AS NUMERIC(20,4)) AS CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_MELAZA_DIF' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA_DIF' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, 0 AS QUINTALES, 
	ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) * 1000 AS KILOGRAMOS, CAST( ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) * (100 / 2.174) AS NUMERIC(20,4)) GALONES, 
	ABS(CAST(E.OBSERVACION AS NUMERIC(20,4))) AS TM, 
	D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.PARENT_ID = D.ID_ES_ENCA
AND E.ID_BODEP = 17 -- ALMAPAC (P)
AND E.ID_BODEGAO = 17 -- ALMAPAC
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA_DIF'

/*
	************************************************************************************************************************
											KARDEX COMPLEMENTARIO DE AZUCAR CRUDO Y MELAZA
	************************************************************************************************************************
*/

DECLARE  @C_PRODUCTO VARCHAR(200),
		 @C_FECHA_REG DATETIME,
		 @C_DOCUMENTO VARCHAR(100),
		 @C_FACT_EXPORT VARCHAR(100),
		 @C_FECHA_FACT DATETIME,
		 @C_CONCEPTO VARCHAR(100),
		 @C_COMPRADOR VARCHAR(100),
		 @C_VAPOR VARCHAR(100),
		 @C_SACOS VARCHAR(100),
		 @C_ENTRADAS NUMERIC(20,4),
		 @C_SALIDAS NUMERIC(20,4),

		 @_ID_ES_ENCA INT, @_ID_PRODUCTO INT, @_ID_TIPO_MOV INT, @_ID_CONCE INT, @_ID_ESPECI INT, @_ID_BODEGAO INT, @_ID_BODEGAD INT, @_CLIENTE VARCHAR(100)
		 
UPDATE KARDEX_UNI$ SET ENTRADAS = 0 WHERE ENTRADAS IS NULL
UPDATE KARDEX_UNI$ SET SALIDAS = 0 WHERE SALIDAS IS NULL
UPDATE KARDEX_UNI$ SET CONCEPTO = LTRIM(RTRIM(CONCEPTO))

DECLARE C1 CURSOR FOR SELECT * FROM KARDEX_UNI$
OPEN C1
FETCH NEXT FROM C1 INTO @C_PRODUCTO, @C_FECHA_REG, @C_DOCUMENTO, @C_FACT_EXPORT, @C_FECHA_FACT, @C_CONCEPTO, @C_COMPRADOR, @C_VAPOR, @C_SACOS, @C_ENTRADAS, @C_SALIDAS
WHILE @@FETCH_STATUS = 0
	BEGIN
	
	SELECT @_ID_PRODUCTO = 	CASE 
			WHEN @C_PRODUCTO = 'AZUCAR CRUDO A GRANEL' THEN 2
			WHEN @C_PRODUCTO = 'MELAZA' THEN 5
			END
	SELECT @_ID_TIPO_MOV = 	CASE 
			WHEN ISNULL(@C_ENTRADAS,0) > 0 THEN 1
			ELSE 2
			END
	SELECT @_ID_CONCE = 	CASE 
			WHEN @C_CONCEPTO = 'EMBARQUES EN PROCESO' THEN 13
			WHEN @C_CONCEPTO = 'LIQUIDACION EMBARQUES EN PROCESO' THEN 6
			WHEN @C_CONCEPTO = 'EXPORTACION' THEN 12
			END
	SELECT @_ID_ESPECI = 	CASE 
			WHEN @C_CONCEPTO = 'EMBARQUES EN PROCESO' THEN 51
			WHEN @C_CONCEPTO = 'LIQUIDACION EMBARQUES EN PROCESO' THEN 54
			WHEN @C_CONCEPTO = 'EXPORTACION' THEN 37
			END
	SELECT @_ID_BODEGAO = 	CASE 
			WHEN @C_CONCEPTO = 'EMBARQUES EN PROCESO' THEN 17
			WHEN @C_CONCEPTO = 'LIQUIDACION EMBARQUES EN PROCESO' THEN 17	
			WHEN @C_CONCEPTO = 'EXPORTACION' THEN 17
			END
	SELECT @_ID_BODEGAD = 	CASE 
			WHEN @C_CONCEPTO = 'EMBARQUES EN PROCESO' THEN 32	
			WHEN @C_CONCEPTO = 'LIQUIDACION EMBARQUES EN PROCESO' THEN 17
			WHEN @C_CONCEPTO = 'EXPORTACION' THEN 32
			END
	SELECT @_CLIENTE = CASE 			
			WHEN @C_CONCEPTO = 'EXPORTACION' THEN @C_COMPRADOR
			ELSE NULL
			END
	SET @_ID_ES_ENCA =  (SELECT ISNULL(MAX(E.ID_ES_ENCA),0)+1 FROM ENTRADA_SALIDA_ENCA E)
	-- Crear encabezado
	INSERT ENTRADA_SALIDA_ENCA
	SELECT 
	@_ID_ES_ENCA AS ID_ES_ENCA,
	@_ID_ES_ENCA AS PARENT_ID, 0 AS COD_CAPTURA, 
	@C_FECHA_REG AS FECHA, 
	@_ID_ES_ENCA AS NUM_DOC,
	NULL AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	10 AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	@_ID_TIPO_MOV AS ID_TIPO_MOV, @_ID_CONCE AS ID_CONCE, @_ID_ESPECI AS ID_ESPECI, @_ID_BODEGAO AS ID_BODEGAO, @_ID_BODEGAD AS ID_BODEGAD,
	'DBO_ADMINPT_KARDEX' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_KARDEX' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	NULL AS ID_ORDEN_TRAS,
	NULL AS ID_PROV_TRAS,
	NULL AS ID_TRANSPORTE,
	NULL AS MOTORISTA,
	NULL AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	@_CLIENTE AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	NULL AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	NULL AS OBSERVACION_RGTRASLADO,
	NULL AS FECHA_RGTRASLADO, NULL AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO 
	
	-- Crear detalle
	INSERT ENTRADA_SALIDA_DETA
	SELECT 
	(SELECT ISNULL(MAX(D.ID_ES_DETA),0) + 1 FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	@_ID_ES_ENCA AS ID_ES_ENCA,
	@C_FECHA_REG AS FECHA, NULL AS NUM_DOC, @_ID_PRODUCTO AS ID_PRODUCTO, 6 AS ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, (@C_ENTRADAS + @C_SALIDAS) AS CANTIDAD, NULL AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_KARDEX' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_KARDEX' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	NULL AS FACTORKG, 0 AS QUINTALES, 
	(  (@C_ENTRADAS + @C_SALIDAS)  *1000) AS KILOGRAMOS, 0 AS GALONES, 
	(@C_ENTRADAS + @C_SALIDAS) AS TM, 
	NULL AS TM_JIBOA,
	NULL AS TM_ALMAPAC, NULL AS TM_DIF_ALMAPAC, NULL AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  NULL AS PESOKG, 17 AS ID_BODEP

	-- Crear info complementaria
	INSERT ENTRA_SALIDA_COMP
	SELECT (SELECT ISNULL(MAX(ID_ES_COMP),0) + 1 FROM ENTRA_SALIDA_COMP) AS ID_ES_COMP,
	@_ID_ES_ENCA AS ID_ES_ENCA,
	@C_FACT_EXPORT AS FAC_NUM, @C_FECHA_FACT AS FAC_FECHA, @C_VAPOR AS VAPOR, 'DBO_ADMINPT_KARDEX' AS USUARIO_CREA, GETDATE() AS FECHA_CREA

	FETCH NEXT FROM C1 INTO @C_PRODUCTO, @C_FECHA_REG, @C_DOCUMENTO, @C_FACT_EXPORT, @C_FECHA_FACT, @C_CONCEPTO, @C_COMPRADOR, @C_VAPOR, @C_SACOS, @C_ENTRADAS, @C_SALIDAS
	END
CLOSE C1
DEALLOCATE C1

--select * from ENTRADA_SALIDA_ENCA where USUARIO_CREA = 'DBO_ADMINPT_KARDEX'
-- DELETE FROM ENTRA_SALIDA_COMP
-- DELETE FROM ENTRA_SALIDA_COMP

/*
	***********************************************************
	IMPORTACION DE ENSACADO ARCHIVO ALMAPAC
	***********************************************************
*/
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY E.ID_ES_ENCA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	E.ID_ES_ENCA AS PARENT_ID, E.COD_CAPTURA, 
	E.FECHA, 
	E.NUM_DOC,
	E.NUM_DOC_PESOS, E.ES_PROPIO, E.ES_AJENO, 
	E.ID_ZAFRA_PROD, E.ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	E.ID_ORDEN_TRAS,
	E.ID_PROV_TRAS,
	E.ID_TRANSPORTE,
	E.MOTORISTA,
	E.NIT,
	E.PLACA_CABEZAL, E.PLACA_REMOLQUE, E.CONTENEDOR, E.MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	E.ENCCLIENTE, E.ENCNIT, E.ENCNRC, E.ENCDEPARTAMENTO, E.ENCMUNICIPIO, E.ENCGIRO, E.ENCDIRECCION, 
	E.FECHADESPACHO,
	1 AS ID_TIPO, 17 AS ID_BODEP, E.ID_FMPAGO, E.EFECTIVO, E.CHEQUE, E.NOTAABONO, E.TOTAL, E.NCUENTA, E.NCHEQUE,
	E.BANCO, E.ID_ESTIBA, E.TENDIDO, E.FECHA_PRODUCCION, E.COLOR, E.FECHA_PRODUCCION1, 
	E.OBSERVACION_RGTRASLADO,
	E.FECHA_RGTRASLADO, E.NUM_DOC_ALMPAC, E.ID_CLIENTEEXP, E.ID_CLIENTEING, E.DONACION, E.MCHEQUE,
	E.MNOTAABONO
FROM ENTRADA_SALIDA_ENCA E
WHERE E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND (SELECT COUNT(1) FROM ENTRADA_SALIDA_DETA D WHERE D.ID_ES_ENCA = E.ID_ES_ENCA AND D.ID_PRODUCTO NOT IN(2,5)) > 0 -- ENSACADO
AND (SELECT COUNT(1) FROM ENSACADO$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN ENSACADO$

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY D.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	E.ID_ES_ENCA,
	D.FECHA, D.NUM_DOC, D.ID_PRODUCTO, D.ID_PRESEN_TRAS, D.ID_UNIDAD_FAC, D.CANTIDAD, D.FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_ENSACADO' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_ENSACADO' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	D.FACTORKG, D.QUINTALES, D.KILOGRAMOS, D.GALONES, (D.KILOGRAMOS / 1000) AS TM, D.TM_JIBOA,
	D.TM_ALMAPAC, D.TM_DIF_ALMAPAC, D.TM_DIF_JIBOA, 
	D.FACTORTM,  D.PESOKG, 17 AS ID_BODEP
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND E.ID_BODEGAO = 29 -- JIBOA
AND E.ID_BODEGAD = 17 -- ALMAPAC
AND E.ID_TIPO_MOV = 2 -- SALIDAS
AND E.ID_ZAFRA_ACTUAL = 10 -- ZAFRA 22/23
AND D.ID_PRODUCTO NOT IN(2,5) -- ENSACADO
AND (SELECT COUNT(1) FROM ENSACADO$ C WHERE CAST(C.DOC_JIBOA_ALMAPAC AS INT) = CAST(E.NUM_DOC AS INT)) > 0 -- EXISTE EN ENSACADO$








INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS PARENT_ID, 0 AS COD_CAPTURA, 
	C.FECHA, 
	C.DOCUM_ALMAPAC AS NUM_DOC, 
	0 AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	(SELECT E.ID_ZAFRA_PROD FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_ENSACADO' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_ENSACADO' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	ISNULL((SELECT E.ID_ORDEN_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS ID_ORDEN_TRAS,
	(SELECT E.ID_PROV_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_PROV_TRAS,
	(SELECT E.ID_TRANSPORTE FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_TRANSPORTE,
	(SELECT E.MOTORISTA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS MOTORISTA,
	(SELECT E.NIT FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	NULL AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	(SELECT E.FECHADESPACHO FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	ISNULL((SELECT E.NUM_DOC FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS OBSERVACION_RGTRASLADO,
	C.FECHA_ALMAPAC AS FECHA_RGTRASLADO, C.DOCUM_ALMAPAC AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO
FROM ENSACADO$ C

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO') AS ID_ES_ENCA,
	C.FECHA, C.NUM_DOC, 	
	(
		SELECT TOP 1 Y.ID_PRODUCTO FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO' AND E.PARENT_ID = Y.ID_ES_ENCA 
	) AS ID_PRODUCTO, 4 AS ID_PRESEN_TRAS, 6 AS ID_UNIDAD_FAC, (C.TM_JIBOA_ALMAPAC * 1000) / 50 AS CANTIDAD, 1.087000 AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_ENSACADO' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_ENSACADO' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 AS FACTORKG, 
	(
		SELECT Y.QUINTALES FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO' AND E.PARENT_ID = Y.ID_ES_ENCA 
	)  AS QUINTALES, (C.TM_JIBOA_ALMAPAC * 1000) AS KILOGRAMOS, 0 AS GALONES, C.TM_JIBOA_ALMAPAC AS TM, C.TM_JIBOA_ALMAPAC AS TM_JIBOA,
	C.TM_ALMAPAC AS TM_ALMAPAC, C.TM_ALMAPAC - C.TM_JIBOA_ALMAPAC AS TM_DIF_ALMAPAC, 0 AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  C.TM_JIBOA_ALMAPAC * 1000 AS PESOKG, 17 AS ID_BODEP
FROM ENSACADO$ C

SELECT DISTINCT P.NOMBRE_PRODUCTO FROM ENTRADA_SALIDA_DETA D, PRODUCTO P WHERE D.ID_PRODUCTO = P.ID_PRODUCTO AND D.USUARIO_CREA LIKE 'DBO_ADMINPT%'



/*
DELETE FROM DIFERENCIAS_ALMAPAC
DELETE FROM ENTRA_SALIDA_COMP
DELETE FROM ENTRADA_SALIDA_DETA WHERE (SELECT COUNT(1) FROM ENTRADA_SALIDA_ENCA E WHERE E.ID_ES_ENCA = ENTRADA_SALIDA_DETA.ID_ES_ENCA AND E.ID_BODEP = 17 AND E.FECHA >= convert(datetime,'01/11/2022',103)) > 0
DELETE FROM ENTRADA_SALIDA_ENCA WHERE ID_BODEP = 17 AND FECHA >= convert(datetime,'01/11/2022',103)


SELECT * FROM ENTRADA_SALIDA_ENCA WHERE ID_BODEP = 17 AND ID_ZAFRA_ACTUAL = 10
*/














/*
ID_TIPO_MOV	NOMBRE_MOV
1	ENTRADAS / INGRESOS
2	SALIDAS / EGRESOS

17	ALMAPAC
29	INJIBOA-1

SELECT * FROM TIPO_MOVIMIENTO
SELECT * FROM CONCEPTO_MOVI WHERE ID_TIPO_MOV = 1
SELECT * FROM CONCEPTO_MOVI WHERE ID_TIPO_MOV = 2
SELECT * FROM ESPECI_MOV WHERE ID_CONCE = 3
SELECT * FROM ESTADO_MOVIMIENTOS
SELECT * FROM TIPO_DOCTO

*/
