USE ADMINPT
GO

/*
CREATE TABLE DIFERENCIAS_ALMAPAC(
	ID_DIF_ALMA INT,
	ID_ES_ENCA INT,
	FECHA_ALMA DATETIME,
	NUM_DOC_ALMA VARCHAR(100),
	TM_JIBOA NUMERIC(20,4),
	TM_ALMA NUMERIC(20,4),
	TM_DIF_ALMA NUMERIC(20,4),
	TM_DIF_JIBOA NUMERIC(20,4),
	CONSTRAINT PK_ENTRADA_SALIDA_ALMA PRIMARY KEY (ID_DIF_ALMA),
	CONSTRAINT FK_ENTRADA_SALIDA_ALMA01 FOREIGN KEY(ID_ES_ENCA) REFERENCES ENTRADA_SALIDA_ENCA (ID_ES_ENCA)
)*/
/*
	***********************************************************
	IMPORTACION DE CARGA AZUCAR CRUDA ARCHIVO ALMAPAC
	***********************************************************
*/
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS PARENT_ID, 0 AS COD_CAPTURA, 
	C.FECHA, 
	C.DOCUM_ALMAPAC AS NUM_DOC, 
	0 AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	(SELECT E.ID_ZAFRA_PROD FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	ISNULL((SELECT E.ID_ORDEN_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS ID_ORDEN_TRAS,
	(SELECT E.ID_PROV_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_PROV_TRAS,
	(SELECT E.ID_TRANSPORTE FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_TRANSPORTE,
	(SELECT E.MOTORISTA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS MOTORISTA,
	(SELECT E.NIT FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	NULL AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	(SELECT E.FECHADESPACHO FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	ISNULL((SELECT E.NUM_DOC FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS OBSERVACION_RGTRASLADO,
	C.FECHA_ALMAPAC AS FECHA_RGTRASLADO, C.DOCUM_ALMAPAC AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO
FROM ADMINPT_REPO..CRUDA$ C

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_CRUDA') AS ID_ES_ENCA,
	C.FECHA, C.NUM_DOC, 2 AS ID_PRODUCTO, 5 AS ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, C.TM_JIBOA_ALMAPAC AS CANTIDAD, 0 AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 AS FACTORKG, 0 AS QUINTALES, 0 AS KILOGRAMOS, 0 AS GALONES, C.TM_JIBOA_ALMAPAC AS TM, C.TM_JIBOA_ALMAPAC AS TM_JIBOA,
	C.TM_ALMAPAC AS TM_ALMAPAC, C.TM_ALMAPAC - C.TM_JIBOA_ALMAPAC AS TM_DIF_ALMAPAC, 0 AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  C.TM_JIBOA_ALMAPAC * 1000 AS PESOKG, 17 AS ID_BODEP
FROM ADMINPT_REPO..CRUDA$ C


/*
	***********************************************************
	IMPORTACION DE MELAZA ARCHIVO ALMAPAC
	***********************************************************
*/
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS PARENT_ID, 0 AS COD_CAPTURA, 
	C.FECHA, 
	C.DOCUM_ALMAPAC AS NUM_DOC, 
	0 AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	(SELECT E.ID_ZAFRA_PROD FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	ISNULL((SELECT E.ID_ORDEN_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS ID_ORDEN_TRAS,
	(SELECT E.ID_PROV_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_PROV_TRAS,
	(SELECT E.ID_TRANSPORTE FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_TRANSPORTE,
	(SELECT E.MOTORISTA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS MOTORISTA,
	(SELECT E.NIT FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	NULL AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	(SELECT E.FECHADESPACHO FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	ISNULL((SELECT E.NUM_DOC FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS OBSERVACION_RGTRASLADO,
	C.FECHA_ALMAPAC AS FECHA_RGTRASLADO, C.DOCUM_ALMAPAC AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO
FROM ADMINPT_REPO..MELAZA$ C

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA') AS ID_ES_ENCA,
	C.FECHA, C.NUM_DOC, 5 AS ID_PRODUCTO, 5 AS ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, C.TM_JIBOA_ALMAPAC AS CANTIDAD, 
	(
		SELECT TOP 1 Y.FACTOR FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA' AND E.PARENT_ID = Y.ID_ES_ENCA 
	) AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_MELAZA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_MELAZA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	0 AS FACTORKG, 0 AS QUINTALES, 0 AS KILOGRAMOS, 
	(
		SELECT Y.GALONES FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_MELAZA' AND E.PARENT_ID = Y.ID_ES_ENCA 
	) AS GALONES, 
	C.TM_JIBOA_ALMAPAC AS TM, C.TM_JIBOA_ALMAPAC AS TM_JIBOA,
	C.TM_ALMAPAC AS TM_ALMAPAC, CAST(C.TM_ALMAPAC - C.TM_JIBOA_ALMAPAC AS NUMERIC(10,5)) AS TM_DIF_ALMAPAC, 0 AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  C.TM_JIBOA_ALMAPAC * 1000 AS PESOKG, 17 AS ID_BODEP
FROM ADMINPT_REPO..MELAZA$ C


/*
	***********************************************************
	IMPORTACION DE ENSACADO ARCHIVO ALMAPAC
	***********************************************************
*/
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS PARENT_ID, 0 AS COD_CAPTURA, 
	C.FECHA, 
	C.DOCUM_ALMAPAC AS NUM_DOC, 
	0 AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	(SELECT E.ID_ZAFRA_PROD FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_ENSACADO' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_ENSACADO' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	ISNULL((SELECT E.ID_ORDEN_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS ID_ORDEN_TRAS,
	(SELECT E.ID_PROV_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_PROV_TRAS,
	(SELECT E.ID_TRANSPORTE FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_TRANSPORTE,
	(SELECT E.MOTORISTA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS MOTORISTA,
	(SELECT E.NIT FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	NULL AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	(SELECT E.FECHADESPACHO FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	ISNULL((SELECT E.NUM_DOC FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS OBSERVACION_RGTRASLADO,
	C.FECHA_ALMAPAC AS FECHA_RGTRASLADO, C.DOCUM_ALMAPAC AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO
FROM ADMINPT_REPO..ENSACADO$ C

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO') AS ID_ES_ENCA,
	C.FECHA, C.NUM_DOC, 	
	(
		SELECT TOP 1 Y.ID_PRODUCTO FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO' AND E.PARENT_ID = Y.ID_ES_ENCA 
	) AS ID_PRODUCTO, 4 AS ID_PRESEN_TRAS, 6 AS ID_UNIDAD_FAC, (C.TM_JIBOA_ALMAPAC * 1000) / 50 AS CANTIDAD, 1.087000 AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_ENSACADO' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_ENSACADO' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 AS FACTORKG, 
	(
		SELECT Y.QUINTALES FROM ENTRADA_SALIDA_DETA Y, ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_ENSACADO' AND E.PARENT_ID = Y.ID_ES_ENCA 
	)  AS QUINTALES, (C.TM_JIBOA_ALMAPAC * 1000) AS KILOGRAMOS, 0 AS GALONES, C.TM_JIBOA_ALMAPAC AS TM, C.TM_JIBOA_ALMAPAC AS TM_JIBOA,
	C.TM_ALMAPAC AS TM_ALMAPAC, C.TM_ALMAPAC - C.TM_JIBOA_ALMAPAC AS TM_DIF_ALMAPAC, 0 AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  C.TM_JIBOA_ALMAPAC * 1000 AS PESOKG, 17 AS ID_BODEP
FROM ADMINPT_REPO..ENSACADO$ C

SELECT DISTINCT P.NOMBRE_PRODUCTO FROM ENTRADA_SALIDA_DETA D, PRODUCTO P WHERE D.ID_PRODUCTO = P.ID_PRODUCTO AND D.USUARIO_CREA LIKE 'DBO_ADMINPT%'



/*
	***********************************************************
	***********************************************************
	IMPORTACION DE CARGA AZUCAR CRUDA ARCHIVO ALMAPAC
	***********************************************************
*/
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(E.ID_ES_ENCA),0) FROM ENTRADA_SALIDA_ENCA E) AS ID_ES_ENCA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS PARENT_ID, 0 AS COD_CAPTURA, 
	C.FECHA, 
	C.DOCUM_ALMAPAC AS NUM_DOC, 
	0 AS NUM_DOC_PESOS, 1 AS ES_PROPIO, 0 AS ES_AJENO, 
	(SELECT E.ID_ZAFRA_PROD FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_ZAFRA_PROD, 10 AS ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 4 AS ID_ESPECI, 29 AS ID_BODEGAO, 17 AS ID_BODEGAD,
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	11 AS ID_ESTADO, 
	ISNULL((SELECT E.ID_ORDEN_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS ID_ORDEN_TRAS,
	(SELECT E.ID_PROV_TRAS FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_PROV_TRAS,
	(SELECT E.ID_TRANSPORTE FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS ID_TRANSPORTE,
	(SELECT E.MOTORISTA FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS MOTORISTA,
	(SELECT E.NIT FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS NIT,
	NULL AS PLACA_CABEZAL, NULL AS PLACA_REMOLQUE, NULL AS CONTENEDOR, NULL AS MARCHAMOS, '' AS OBSERVACION, '' AS NFORMULARIO,
	NULL AS ENCCLIENTE, NULL AS ENCNIT, NULL AS ENCNRC, NULL AS ENCDEPARTAMENTO, NULL AS ENCMUNICIPIO, NULL AS ENCGIRO, NULL AS ENCDIRECCION, 
	(SELECT E.FECHADESPACHO FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17) AS FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL AS ID_FMPAGO, NULL AS EFECTIVO, NULL AS CHEQUE, NULL AS NOTAABONO, NULL AS TOTAL, NULL AS NCUENTA, NULL AS NCHEQUE,
	NULL AS BANCO, NULL AS ID_ESTIBA, NULL AS TENDIDO, NULL AS FECHA_PRODUCCION, NULL AS COLOR, NULL AS FECHA_PRODUCCION1, 
	ISNULL((SELECT E.NUM_DOC FROM ENTRADA_SALIDA_ENCA E WHERE CAST(E.NUM_DOC AS FLOAT) = C.NUM_DOC AND E.ID_BODEP = 29 AND E.ID_BODEGAD = 17),0) AS OBSERVACION_RGTRASLADO,
	C.FECHA_ALMAPAC AS FECHA_RGTRASLADO, C.DOCUM_ALMAPAC AS NUM_DOC_ALMPAC, NULL AS ID_CLIENTEEXP, NULL AS ID_CLIENTEING, NULL AS DONACION, NULL AS MCHEQUE,
	NULL AS MNOTAABONO
FROM ADMINPT_REPO..CRUDA$ C

INSERT ENTRADA_SALIDA_DETA
SELECT 
	ROW_NUMBER() OVER(ORDER BY C.FECHA) + (SELECT ISNULL(MAX(D.ID_ES_DETA),0) FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	(SELECT E.ID_ES_ENCA FROM ENTRADA_SALIDA_ENCA E WHERE E.NUM_DOC_ALMPAC = C.DOCUM_ALMAPAC AND E.USUARIO_CREA = 'DBO_ADMINPT_CRUDA') AS ID_ES_ENCA,
	C.FECHA, C.NUM_DOC, 2 AS ID_PRODUCTO, 5 AS ID_PRESEN_TRAS, 4 AS ID_UNIDAD_FAC, C.TM_JIBOA_ALMAPAC AS CANTIDAD, 0 AS FACTOR,
	NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT_CRUDA' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT_CRUDA' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 AS FACTORKG, 0 AS QUINTALES, 0 AS KILOGRAMOS, 0 AS GALONES, C.TM_JIBOA_ALMAPAC AS TM, C.TM_JIBOA_ALMAPAC AS TM_JIBOA,
	C.TM_ALMAPAC AS TM_ALMAPAC, C.TM_ALMAPAC - C.TM_JIBOA_ALMAPAC AS TM_DIF_ALMAPAC, 0 AS TM_DIF_JIBOA, 
	NULL AS FACTORTM,  C.TM_JIBOA_ALMAPAC * 1000 AS PESOKG, 17 AS ID_BODEP
FROM ADMINPT_REPO..CRUDA$ C

--DELETE FROM ENTRADA_SALIDA_DETA WHERE USUARIO_CREA IN('DBO_ADMINPT_CRUDA','DBO_ADMINPT_MELAZA','DBO_ADMINPT_ENSACADO','DBO_ADMINPT')
--DELETE FROM ENTRADA_SALIDA_ENCA WHERE USUARIO_CREA IN('DBO_ADMINPT_CRUDA','DBO_ADMINPT_MELAZA','DBO_ADMINPT_ENSACADO','DBO_ADMINPT')












/*
ID_TIPO_MOV	NOMBRE_MOV
1	ENTRADAS / INGRESOS
2	SALIDAS / EGRESOS

17	ALMAPAC
29	INJIBOA-1

SELECT * FROM TIPO_MOVIMIENTO
SELECT * FROM CONCEPTO_MOVI WHERE ID_TIPO_MOV = 1
SELECT * FROM CONCEPTO_MOVI WHERE ID_TIPO_MOV = 2
SELECT * FROM ESPECI_MOV WHERE ID_CONCE = 3
SELECT * FROM ESTADO_MOVIMIENTOS
SELECT * FROM TIPO_DOCTO

*/
