

DECLARE @ID_ES_ENCA INT
SET @ID_ES_ENCA = (SELECT ISNULL(MAX(ID_ES_ENCA),0) + 1 FROM ENTRADA_SALIDA_ENCA)

INSERT ENTRADA_SALIDA_ENCA
SELECT 
	@ID_ES_ENCA AS ID_ES_ENCA,
	@ID_ES_ENCA AS PARENT_ID, 0 AS COD_CAPTURA, 
	CONVERT(DATETIME,'26/03/2023',103) AS FECHA, 
	@ID_ES_ENCA AS NUM_DOC,
	0 NUM_DOC_PESOS, 1 ES_PROPIO, 0 ES_AJENO, 
	10 ID_ZAFRA_PROD, 10 ID_ZAFRA_ACTUAL, 
	2 AS ID_TIPO_MOV, 12 AS ID_CONCE, 57 AS ID_ESPECI, 17 AS ID_BODEGAO, 29 AS ID_BODEGAD,
	'DBO_ADMINPT' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	5 AS ID_ESTADO, 
	0 ID_ORDEN_TRAS,
	0 ID_PROV_TRAS,
	0 ID_TRANSPORTE,
	NULL MOTORISTA,
	NULL NIT,
	NULL PLACA_CABEZAL, NULL PLACA_REMOLQUE, NULL CONTENEDOR, NULL MARCHAMOS, 'DEVUELTO POR DEGRADACION' OBSERVACION, NULL NFORMULARIO,
	NULL ENCCLIENTE, NULL ENCNIT, NULL ENCNRC, NULL ENCDEPARTAMENTO, NULL ENCMUNICIPIO, NULL ENCGIRO, NULL ENCDIRECCION, 
	CONVERT(DATETIME,'26/03/2023',103) FECHADESPACHO,
	5 AS ID_TIPO, 17 AS ID_BODEP, NULL ID_FMPAGO, NULL EFECTIVO, NULL CHEQUE, NULL NOTAABONO, NULL TOTAL, NULL NCUENTA, NULL NCHEQUE,
	NULL BANCO, NULL ID_ESTIBA, NULL TENDIDO, NULL FECHA_PRODUCCION, NULL COLOR, NULL FECHA_PRODUCCION1, 
	NULL OBSERVACION_RGTRASLADO,
	NULL FECHA_RGTRASLADO, NULL NUM_DOC_ALMPAC, NULL ID_CLIENTEEXP, NULL ID_CLIENTEING, NULL DONACION, NULL MCHEQUE,
	NULL MNOTAABONO

INSERT ENTRADA_SALIDA_DETA
SELECT 
	(SELECT ISNULL(MAX(D.ID_ES_DETA),0) +1 FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	@ID_ES_ENCA AS ID_ES_ENCA,
	CONVERT(DATETIME,'26/03/2023',103) FECHA, @ID_ES_ENCA NUM_DOC, 3 AS ID_PRODUCTO, 2 ID_PRESEN_TRAS,6 ID_UNIDAD_FAC, 592 CANTIDAD, 1.087000 FACTOR, NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 FACTORKG, ROUND(592 * 1.087000, 2) QUINTALES, (592 * 50) KILOGRAMOS, 0 GALONES, 
	ROUND((592 * 50) / 1000, 2) TM, NULL TM_JIBOA, NULL TM_ALMAPAC, NULL TM_DIF_ALMAPAC, NULL TM_DIF_JIBOA, NULL FACTORTM, NULL PESOKG, 17 ID_BODEP

-- ============================================================================================================================
DECLARE @ID_ES_ENCA INT
SET @ID_ES_ENCA =  (SELECT ISNULL(MAX(ID_ES_ENCA),0) + 1 FROM ENTRADA_SALIDA_ENCA)
INSERT ENTRADA_SALIDA_ENCA
SELECT 
	@ID_ES_ENCA AS ID_ES_ENCA,
	@ID_ES_ENCA AS PARENT_ID, 0 AS COD_CAPTURA, 
	CONVERT(DATETIME,'26/03/2023',103) AS FECHA, 
	@ID_ES_ENCA AS NUM_DOC,
	0 NUM_DOC_PESOS, 1 ES_PROPIO, 0 ES_AJENO, 
	10 ID_ZAFRA_PROD, 10 ID_ZAFRA_ACTUAL, 
	1 AS ID_TIPO_MOV, 3 AS ID_CONCE, 56 AS ID_ESPECI, 17 AS ID_BODEGAO, 29 AS ID_BODEGAD,
	'DBO_ADMINPT' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	5 AS ID_ESTADO, 
	0 ID_ORDEN_TRAS,
	0 ID_PROV_TRAS,
	0 ID_TRANSPORTE,
	NULL MOTORISTA,
	NULL NIT,
	NULL PLACA_CABEZAL, NULL PLACA_REMOLQUE, NULL CONTENEDOR, NULL MARCHAMOS, 'DEVUELTO POR DEGRADACION' OBSERVACION, NULL NFORMULARIO,
	NULL ENCCLIENTE, NULL ENCNIT, NULL ENCNRC, NULL ENCDEPARTAMENTO, NULL ENCMUNICIPIO, NULL ENCGIRO, NULL ENCDIRECCION, 
	CONVERT(DATETIME,'26/03/2023',103) FECHADESPACHO,
	5 AS ID_TIPO, 29 AS ID_BODEP, NULL ID_FMPAGO, NULL EFECTIVO, NULL CHEQUE, NULL NOTAABONO, NULL TOTAL, NULL NCUENTA, NULL NCHEQUE,
	NULL BANCO, NULL ID_ESTIBA, NULL TENDIDO, NULL FECHA_PRODUCCION, NULL COLOR, NULL FECHA_PRODUCCION1, 
	NULL OBSERVACION_RGTRASLADO,
	NULL FECHA_RGTRASLADO, NULL NUM_DOC_ALMPAC, NULL ID_CLIENTEEXP, NULL ID_CLIENTEING, NULL DONACION, NULL MCHEQUE,
	NULL MNOTAABONO

INSERT ENTRADA_SALIDA_DETA
SELECT 
	(SELECT ISNULL(MAX(D.ID_ES_DETA),0) +1 FROM ENTRADA_SALIDA_DETA D) AS ID_ES_DETA,
	@ID_ES_ENCA AS ID_ES_ENCA,
	CONVERT(DATETIME,'26/03/2023',103) FECHA, @ID_ES_ENCA NUM_DOC, 3 AS ID_PRODUCTO, 2 ID_PRESEN_TRAS,6 ID_UNIDAD_FAC, 592 CANTIDAD, 1.087000 FACTOR, NEWID() AS REFERENCIA_DETA, 
	'DBO_ADMINPT' AS USUARIO_CREA, GETDATE() AS FECHA_CREA, 'DBO_ADMINPT' AS USUARIO_ACT, GETDATE() AS FECHA_ACT,
	50 FACTORKG, ROUND(592 * 1.087000, 2) QUINTALES, (592 * 50) KILOGRAMOS, 0 GALONES, 
	ROUND((592 * 50) / 1000, 2) TM, NULL TM_JIBOA, NULL TM_ALMAPAC, NULL TM_DIF_ALMAPAC, NULL TM_DIF_JIBOA, NULL FACTORTM, NULL PESOKG, 29 ID_BODEP