
DECLARE @CODIGO INT,
		@CONTAR INT,
		@ACUM INT,
		@MAX INT,
		@MAX2 INT,
		@MIN INT,
		@CUR_LLAVE INT,
		@LLAVE INT,
		@SQL VARCHAR(1000),
		@SALDO NUMERIC(20,4)



SELECT 
CAST(0 AS INT) AS LLAVE,
CAST(0 AS INT) AS CORRELATIVO,
A.ID_ES_ENCA,
A.ID_BODEP,
A.ID_ZAFRA_ACTUAL, 
A.ID_ZAFRA_PROD, 
B.ID_UNIDAD_FAC,
B.ID_PRESEN_TRAS, 
A.ID_TIPO_MOV,
A.ID_ESTADO, 
(SELECT EM.NOMBRE_ESTADO FROM ESTADO_MOVIMIENTOS EM WHERE EM.ID_ESTADO=A.ID_ESTADO) AS ESTADO,
 (SELECT B.NOMBRE FROM BODEGA B WHERE B.ID_BODEGA=A.ID_BODEP) AS BODEGA_PRINCIPAL,
 (SELECT B.NOMBRE FROM BODEGA B WHERE B.ID_BODEGA=A.ID_BODEGAO) AS ORIGEN,
 CASE
 WHEN A.ID_BODEGAD=0 THEN A.ENCCLIENTE
 ELSE (SELECT B.NOMBRE FROM BODEGA B WHERE B.ID_BODEGA=A.ID_BODEGAD)END AS DESTINO,
   A.FECHA,
  A.NUM_DOC,
  (select t.NOMBRE_TIPO from TIPO_DOCTO t where t.ID_TIPO = a.ID_TIPO) as TIPO_DOCUMENTO,
  A.FECHADESPACHO,  
  IIF(A.ID_TIPO_MOV = 1,'E','S') AS TIPO_MOVIMIENTO,
  (SELECT TP.NOMBRE_MOV FROM TIPO_MOVIMIENTO TP WHERE TP.ID_TIPO_MOV=A.ID_TIPO_MOV) AS TP_MOVIMIENTO,
 (SELECT CM.NOMBRE_CONCE FROM CONCEPTO_MOVI CM WHERE CM.ID_CONCE=A.ID_CONCE) AS CONCEPTO,
 (SELECT T.NOMBRE_ESPECI FROM ESPECI_MOV T WHERE T.ID_ESPECI = A.ID_ESPECI) AS ESPECIFICO,
 B.ID_PRODUCTO,
 (SELECT P.NOMBRE_KARDEX FROM PRODUCTO P WHERE P.ID_PRODUCTO=B.ID_PRODUCTO) AS NPRODUCTO,
 (SELECT T.NOMBRE_UNIDAD FROM UNIDAD_MEDI_FAC T WHERE T.ID_UNIDAD_FAC = B.ID_UNIDAD_FAC) AS UNIDAD,
 (select Z.NOMBRE_ZAFRA from zafra z where z.ID_ZAFRA = A.ID_ZAFRA_ACTUAL) AS ZAFRA_EJECUCION, 
 (select Z.NOMBRE_ZAFRA from zafra z where z.ID_ZAFRA = A.ID_ZAFRA_PROD) AS ZAFRA_PRODUCTO, 
 A.OBSERVACION,
 (select TOP 1 cast(P.BRUTO * 0.453592 as numeric(20,2)) from BASCULA_DETA_ES P where P.ID_ES_ENCA = B.ID_ES_ENCA and P.ID_PRODUCTO = B.ID_PRODUCTO ) as BRUTO,
 (select TOP 1 cast(P.TARA * 0.453592 as numeric(20,2)) from BASCULA_DETA_ES P where P.ID_ES_ENCA = B.ID_ES_ENCA and P.ID_PRODUCTO = B.ID_PRODUCTO ) as TARA,
 (select  TOP 1 cast(P.NETO * 0.453592 as numeric(20,2)) from BASCULA_DETA_ES P where P.ID_ES_ENCA = B.ID_ES_ENCA and P.ID_PRODUCTO = B.ID_PRODUCTO ) as NETO,
 A.FECHA_CREA,
  B.CANTIDAD,  
 CASE 
 WHEN  B.ID_PRODUCTO IN (1,3,4,20) THEN (B.CANTIDAD)*50
  WHEN  B.ID_PRODUCTO IN (6,7,8) THEN (B.CANTIDAD)*1250
  WHEN  B.ID_PRODUCTO IN (21,22) THEN (B.CANTIDAD)*25
  WHEN  B.ID_PRODUCTO IN (2) THEN ROUND( ((B.CANTIDAD)*100) / 2.174, 2)
  ELSE 0 END KG,
   CASE 
 WHEN  B.ID_PRODUCTO IN (1,3,4,20) THEN (B.CANTIDAD)*1.087
  WHEN  B.ID_PRODUCTO IN (6,7,8) THEN (B.CANTIDAD)*27.18
  WHEN  B.ID_PRODUCTO IN (21,22) THEN (B.CANTIDAD)*0.5435
  WHEN  B.ID_PRODUCTO IN (2) THEN (B.CANTIDAD)  ELSE 0 END QQ,
CASE WHEN  B.ID_PRODUCTO IN (5) THEN (B.CANTIDAD)  ELSE 0 END GAL,
A.ENCCLIENTE AS COMPRADOR,
(SELECT C.BOOKING FROM ENTRA_SALIDA_COMP C WHERE C.ID_ES_ENCA = A.ID_ES_ENCA) AS BOOKING,
(SELECT C.VAPOR FROM ENTRA_SALIDA_COMP C WHERE C.ID_ES_ENCA = A.ID_ES_ENCA) AS VAPOR,
(SELECT C.FAC_NUM FROM ENTRA_SALIDA_COMP C WHERE C.ID_ES_ENCA = A.ID_ES_ENCA) AS FACTURA,
(SELECT C.FAC_FECHA FROM ENTRA_SALIDA_COMP C WHERE C.ID_ES_ENCA = A.ID_ES_ENCA) AS FECHA_FAC,
CAST(0 AS NUMERIC(20,4)) AS SALDO_INICIAL,
IIF(A.ID_TIPO_MOV = 1 AND A.ID_ESTADO <> 8 , B.CANTIDAD, 0) AS ENTRADAS,
IIF(A.ID_TIPO_MOV = 2 AND A.ID_ESTADO <> 8, B.CANTIDAD, 0) AS SALIDAS,
CAST(0 AS NUMERIC(20,4)) AS SALDO_FINAL
INTO #FULL
FROM
  dbo.ENTRADA_SALIDA_ENCA A
  INNER JOIN dbo.ENTRADA_SALIDA_DETA B ON (A.ID_ES_ENCA = B.ID_ES_ENCA)
WHERE A.FECHADESPACHO <= CONVERT(DATETIME,'30/06/2023',103)


  
CREATE TABLE #E(
	LLAVE INT,
	ID_BODEP INT,
	ID_PRODUCTO INT,
	NOMBRE_PRODUCTO VARCHAR(300),
	ID_ZAFRA_EJEC INT,
	ID_ZAFRA_PROD INT,
	ID_MARCA INT,
	ID_TIPO_PROD INT,
	ID_UNIDAD_FAC INT,
	ID_PRESEN_TRAS INT,
	FECHA_PRIM DATETIME,
	FECHA_ULT DATETIME,
	SALDO_I NUMERIC(20,4),
	ENTRADAS NUMERIC(20,4),
	SALIDAS NUMERIC(20,4),
	SALDO_F NUMERIC(20,4),
)

CREATE TABLE #PROD_ZAFRA_FAB(	
	LLAVE INT,
	ID_BODEP INT,
	ID_PRODUCTO INT,		
	ID_ZAFRA_PROD INT,	
	ID_MARCA INT,
	ID_TIPO_PROD INT,
	ID_UNIDAD_FAC INT,
	ID_PRESEN_TRAS INT,
	FECHA_PRIM DATETIME,
	FECHA_ULT DATETIME,
	ENTRADAS NUMERIC(20,4),
	SALIDAS NUMERIC(20,4),
	SALDO_F NUMERIC(20,4)
)


-- Generando resumen por Bodega / Producto / Zafra ejecución / Zafra producto
INSERT #E
SELECT 
	ROW_NUMBER() OVER(ORDER BY ID_BODEP, ID_PRODUCTO, ID_ZAFRA_ACTUAL, ID_ZAFRA_PROD) AS LLAVE,
	ID_BODEP, ID_PRODUCTO, NOMBRE_PRODUCTO, ID_ZAFRA_ACTUAL, ID_ZAFRA_PROD, ID_MARCA, ID_TIPO_PROD, ID_UNIDAD_FAC, ID_PRESEN_TRAS, FECHA_PRIM, FECHA_ULT,
	0 AS SALDO_INICIAL, 0 AS ENTRADAS, 0 AS SALIDAS, 0 AS SALDO_FINAL
FROM (
SELECT	L.ID_BODEP, L.ID_PRODUCTO, (SELECT P.NOMBRE_PRODUCTO FROM PRODUCTO P WHERE P.ID_PRODUCTO = L.ID_PRODUCTO) AS NOMBRE_PRODUCTO, L.ID_ZAFRA_ACTUAL, L.ID_ZAFRA_PROD, 
		P.ID_MARCA, P.ID_TIPO_PROD, L.ID_UNIDAD_FAC, L.ID_PRESEN_TRAS, MIN(L.FECHADESPACHO) AS FECHA_PRIM, MAX(L.FECHADESPACHO) AS FECHA_ULT		
FROM #FULL L, PRODUCTO P
WHERE L.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY L.ID_BODEP, L.ID_PRODUCTO, L.ID_ZAFRA_ACTUAL, L.ID_ZAFRA_PROD, P.ID_MARCA, P.ID_TIPO_PROD, L.ID_UNIDAD_FAC, L.ID_PRESEN_TRAS
) S
ORDER BY ID_BODEP, ID_PRODUCTO, ID_ZAFRA_ACTUAL, ID_ZAFRA_PROD, ID_UNIDAD_FAC, ID_PRESEN_TRAS

-- Generando resumen por Bodega / Producto / Zafra producto (solo para generar kardex)
INSERT #PROD_ZAFRA_FAB
SELECT 
	ROW_NUMBER() OVER(ORDER BY ID_BODEP, ID_PRODUCTO, ID_ZAFRA_PROD) AS LLAVE, ID_BODEP, ID_PRODUCTO, ID_ZAFRA_PROD, ID_MARCA, ID_TIPO_PROD, ID_UNIDAD_FAC, ID_PRESEN_TRAS,
	NULL, NULL, 0, 0, 0
FROM(
	SELECT DISTINCT ID_BODEP, ID_PRODUCTO, ID_ZAFRA_PROD, ID_MARCA, ID_TIPO_PROD, ID_UNIDAD_FAC, ID_PRESEN_TRAS 
	FROM #E 
) T
ORDER BY ID_BODEP, ID_PRODUCTO, ID_ZAFRA_PROD, ID_MARCA, ID_TIPO_PROD, ID_UNIDAD_FAC, ID_PRESEN_TRAS 


-- Actualizando movimientos con la LLAVE #PROD_ZAFRA_FAB
UPDATE X
	SET X.LLAVE = E.LLAVE
FROM #FULL X, #PROD_ZAFRA_FAB E
WHERE X.ID_BODEP = E.ID_BODEP
AND X.ID_PRODUCTO = E.ID_PRODUCTO
AND X.ID_ZAFRA_PROD = E.ID_ZAFRA_PROD
AND X.ID_UNIDAD_FAC = E.ID_UNIDAD_FAC
AND X.ID_PRESEN_TRAS = E.ID_PRESEN_TRAS

/*
	GENERACION DE SALDOS
*/
SET @MAX = (SELECT MAX(LLAVE) FROM #PROD_ZAFRA_FAB)
SET @LLAVE = 1
SET @CONTAR = 1

WHILE (@LLAVE < = @MAX)
	BEGIN
	-- Asignando correlativos por LLAVE
	UPDATE X
		SET X.CORRELATIVO = J.ID
	FROM #FULL X, 
		(SELECT TOP 100 PERCENT ID_ES_ENCA, ROW_NUMBER() OVER(ORDER BY FECHADESPACHO, FECHA_CREA) AS ID FROM #FULL T WHERE T.LLAVE = @LLAVE ORDER BY T.FECHADESPACHO, T.FECHA_CREA) J
	WHERE X.LLAVE = @LLAVE
	AND X.ID_ES_ENCA = J.ID_ES_ENCA

	-- Generando Kardex
	SET @SALDO = 0
	SET @ACUM = 1
	SET @MAX2 = (SELECT MAX(CORRELATIVO) FROM #FULL WHERE LLAVE = @LLAVE)
	WHILE @ACUM <= @MAX2
		BEGIN
			
		SET @SQL = 'UPDATE #FULL SET SALDO_INICIAL = ' + CAST(@SALDO AS VARCHAR) + ', SALDO_FINAL = ' + CAST(@SALDO AS VARCHAR) + ' + IIF(FECHADESPACHO IS NULL, 0, ENTRADAS) - IIF(FECHADESPACHO IS NULL, 0, SALIDAS) WHERE LLAVE = ' + CAST(@LLAVE AS VARCHAR) + ' AND CORRELATIVO = ' + CAST(@ACUM AS VARCHAR)
		EXEC(@SQL)
		SET @SALDO = (SELECT SUM(SALDO_FINAL) FROM #FULL WHERE LLAVE = @LLAVE AND CORRELATIVO = @ACUM)

		SET @ACUM = @ACUM + 1
		END

	SET @LLAVE = @LLAVE + 1
	END

-- ACTUALIZANDO SALDOS DE #PROD_ZAFRA_FAB
UPDATE #PROD_ZAFRA_FAB
SET 		
		FECHA_PRIM =  (SELECT MIN(FECHADESPACHO) FROM #FULL F WHERE F.LLAVE = #PROD_ZAFRA_FAB.LLAVE),
		FECHA_ULT =  (SELECT MAX(FECHADESPACHO) FROM #FULL F WHERE F.LLAVE = #PROD_ZAFRA_FAB.LLAVE),
		ENTRADAS =  (SELECT SUM(ENTRADAS) FROM #FULL F WHERE F.LLAVE = #PROD_ZAFRA_FAB.LLAVE),
		SALIDAS = (SELECT SUM(SALIDAS) FROM #FULL F WHERE F.LLAVE = #PROD_ZAFRA_FAB.LLAVE)	
UPDATE #PROD_ZAFRA_FAB SET SALDO_F = ENTRADAS - SALIDAS

-- ACTUALIZANDO/SOBREESCRIBIENDO movimientos con la LLAVE #E
UPDATE #FULL SET LLAVE = NULL

UPDATE X
	SET X.LLAVE = E.LLAVE
FROM #FULL X, #E E
WHERE X.ID_BODEP = E.ID_BODEP
AND X.ID_PRODUCTO = E.ID_PRODUCTO
AND X.ID_ZAFRA_ACTUAL = E.ID_ZAFRA_EJEC
AND X.ID_ZAFRA_PROD = E.ID_ZAFRA_PROD
AND X.ID_UNIDAD_FAC = E.ID_UNIDAD_FAC
AND X.ID_PRESEN_TRAS = E.ID_PRESEN_TRAS

--ACTUALIZAR SALDOS DE #E
UPDATE #E
	SET 
		ENTRADAS =  ISNULL( (SELECT SUM(ENTRADAS) FROM #FULL F WHERE F.LLAVE = #E.LLAVE) , 0),
		SALIDAS =	ISNULL( (SELECT SUM(SALIDAS) FROM #FULL F WHERE F.LLAVE = #E.LLAVE)	, 0)	

UPDATE #E SET SALDO_F = ENTRADAS - SALIDAS 
WHERE ID_ZAFRA_EJEC = ID_ZAFRA_PROD
UPDATE #E SET SALDO_I = ISNULL( (SELECT TOP 1 T.SALDO_F FROM #E T WHERE T.ID_BODEP = #E.ID_BODEP AND T.ID_PRODUCTO = #E.ID_PRODUCTO AND T.ID_ZAFRA_PROD = #E.ID_ZAFRA_PROD AND T.ID_ZAFRA_EJEC < #E.ID_ZAFRA_EJEC ORDER BY ID_ZAFRA_EJEC DESC)  ,0)
WHERE ID_ZAFRA_EJEC <> ID_ZAFRA_PROD 
UPDATE #E SET SALDO_F = SALDO_I + ENTRADAS - SALIDAS 

-- Obtener resumen por Bodega/Producto/Zafra producto
SELECT 	
	B.NOMBRE AS BODEGA,
	E.ID_PRODUCTO AS CODIGO,
	(SELECT P.NOMBRE_PRODUCTO FROM PRODUCTO P WHERE P.ID_PRODUCTO = E.ID_PRODUCTO) AS PRODUCTO,		
	(SELECT Z.NOMBRE_ZAFRA FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA_PROD) AS ZAFRA_PRODUCTO,
	(SELECT T.NOMBRE_MARCA FROM MARCA T WHERE T.ID_MARCA = E.ID_MARCA) AS MARCA,
	(SELECT T.NOMBRE_TIPO FROM TIPO_PRODUCTO T WHERE T.ID_TIPO_PROD = E.ID_TIPO_PROD) AS TIPO,
	(SELECT T.NOMBRE_UNIDAD FROM UNIDAD_MEDI_FAC T WHERE T.ID_UNIDAD_FAC = E.ID_UNIDAD_FAC) AS UNIDAD,
	(SELECT T.NOMBRE_PRESEN_TRAA FROM PRESENTACION_TRAS T WHERE T.ID_PRESEN_TRAS = E.ID_PRESEN_TRAS) AS PRESENTACION,
	E.FECHA_PRIM AS FECHA_PRIMER_MOVIMIENTO,
	E.FECHA_ULT AS FECHA_ULTIMO_MOVIMIENTO,	
	E.ENTRADAS,
	E.SALIDAS,
	E.SALDO_F
FROM #PROD_ZAFRA_FAB E, BODEGA_PRICIPAL B
WHERE E.ID_BODEP = B.ID_BODEP
ORDER BY 1, 2, 3

SELECT 
	E.LLAVE,
	B.NOMBRE AS BODEGA,
	E.ID_PRODUCTO AS CODIGO,
	E.NOMBRE_PRODUCTO AS PRODUCTO,	
	(SELECT Z.NOMBRE_ZAFRA FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA_EJEC) AS ZAFRA_EJECUCION,
	(SELECT Z.NOMBRE_ZAFRA FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA_PROD) AS ZAFRA_PRODUCTO,
	(SELECT T.NOMBRE_MARCA FROM MARCA T WHERE T.ID_MARCA = E.ID_MARCA) AS MARCA,
	(SELECT T.NOMBRE_TIPO FROM TIPO_PRODUCTO T WHERE T.ID_TIPO_PROD = E.ID_TIPO_PROD) AS TIPO,
	(SELECT T.NOMBRE_UNIDAD FROM UNIDAD_MEDI_FAC T WHERE T.ID_UNIDAD_FAC = E.ID_UNIDAD_FAC) AS UNIDAD,
	(SELECT T.NOMBRE_PRESEN_TRAA FROM PRESENTACION_TRAS T WHERE T.ID_PRESEN_TRAS = E.ID_PRESEN_TRAS) AS PRESENTACION,
	E.FECHA_PRIM AS FECHA_PRIMER_MOVIMIENTO,
	E.FECHA_ULT AS FECHA_ULTIMO_MOVIMIENTO,
	E.SALDO_I,
	E.ENTRADAS,
	E.SALIDAS,
	E.SALDO_F
FROM #E E, BODEGA_PRICIPAL B
WHERE E.ID_BODEP = B.ID_BODEP
ORDER BY 1, 2, 3

SELECT 
	LLAVE, ID_ES_ENCA, ESTADO, BODEGA_PRINCIPAL, ORIGEN, DESTINO, FECHA, NUM_DOC, TIPO_DOCUMENTO, FECHADESPACHO, TIPO_MOVIMIENTO, TP_MOVIMIENTO,
	CONCEPTO, ESPECIFICO, ID_PRODUCTO, NPRODUCTO, UNIDAD, ZAFRA_EJECUCION, ZAFRA_PRODUCTO, OBSERVACION, CANTIDAD, KG, QQ, GAL, COMPRADOR, 
	BOOKING, VAPOR, FACTURA, FECHA_FAC, SALDO_INICIAL, ENTRADAS, SALIDAS, SALDO_FINAL
FROM #FULL ORDER BY LLAVE, CORRELATIVO 

DROP TABLE #PROD_ZAFRA_FAB
DROP TABLE #E
DROP TABLE #FULL