SELECT 	
	1 AS CONTROL,
	iif(T.ID_TIPO_MOV = 1, 'ENTRADAS', 'SALIDAS') AS TIPO_MOVIMIENTO,
	C.ID_CONCE, C.NOMBRE_CONCE AS CONCEPTO,
	ID_ESPECI, NOMBRE_ESPECI AS ESPECIFICO,
	'' AS BODEGA
FROM TIPO_MOVIMIENTO T, CONCEPTO_MOVI C, ESPECI_MOV E
WHERE T.ID_TIPO_MOV = C.ID_TIPO_MOV
AND C.ID_CONCE = E.ID_CONCE

UNION ALL

SELECT DISTINCT
1 AS CONTROL,
IIF(E.ID_TIPO_MOV = 1, 'ENTRADAS', 'SALIDAS') AS TIPO_MOVIMIENTO,
E.ID_CONCE, 
(SELECT B.NOMBRE_CONCE FROM CONCEPTO_MOVI B WHERE B.ID_CONCE = E.ID_CONCE) AS CONCEPTO,
E.ID_ESPECI,
(SELECT B.NOMBRE_ESPECI FROM ESPECI_MOV B WHERE B.ID_ESPECI = E.ID_ESPECI) AS ESPECIFICO,
CASE
	WHEN E.ID_BODEP = 0 THEN '4. INTEGRADOR ADMIN-PT'
	WHEN E.ID_BODEP = 16 THEN '2. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
	WHEN E.ID_BODEP = 17 THEN '3. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
	WHEN E.ID_BODEP = 29 THEN '1. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
	ELSE '4. INTEGRADOR ADMIN-PT'
END AS BODEGA
FROM ENTRADA_SALIDA_ENCA E

-- =================================================================================================================

SELECT (SELECT T.NOMBRE_TIPO FROM TIPO_PRODUCTO T WHERE T.ID_TIPO_PROD = P.ID_TIPO_PROD) AS TIPO, P.NOMBRE_PRODUCTO AS PRODUCTO, '' AS BODEGA
FROM PRODUCTO P
UNION ALL
SELECT DISTINCT
	T.NOMBRE_TIPO AS TIPO, P.NOMBRE_PRODUCTO AS PRODUCTO, 
	CASE
		WHEN E.ID_BODEP = 0 THEN '4. INTEGRADOR ADMIN-PT'
		WHEN E.ID_BODEP = 16 THEN '2. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
		WHEN E.ID_BODEP = 17 THEN '3. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
		WHEN E.ID_BODEP = 29 THEN '1. ' + (SELECT B.NOMBRE FROM BODEGA_PRICIPAL B WHERE B.ID_BODEP = E.ID_BODEP)
		ELSE '4. INTEGRADOR ADMIN-PT'
	END AS BODEGA
FROM ENTRADA_SALIDA_ENCA E, ENTRADA_SALIDA_DETA D, PRODUCTO P, TIPO_PRODUCTO T
WHERE E.ID_ES_ENCA = D.ID_ES_ENCA
AND D.ID_PRODUCTO = P.ID_PRODUCTO
AND P.ID_TIPO_PROD = T.ID_TIPO_PROD


SELECT * FROM PRODUCTO

