SELECT * FROM PRODUCTO
SELECT * FROM TIPO_PRODUCTO
SELECT * FROM PRESENTACION_TRAS
SELECT * FROM ESTADO_MOVIMIENTOS
SELECT * FROM ESPECI_MOV
SELECT * FROM TIPO_DOCTO

UPDATE PRODUCTO 
SET NOMBRE_PRODUCTO = 'AZUCAR CRUDA ENSACADA' ,
	NOMBRE_KARDEX = 'AZUCAR CRUDA ENSACADA',
	NOMBRE_VENTA = 'AZUCAR CRUDA ENSACADA',
	RPT = 'AZUCAR CRUDA ENSACADA'
WHERE ID_PRODUCTO = 15

SELECT 
	T.ID_TIPO_MOV, T.NOMBRE_MOV AS TIPO_MOVIMIENTO,
	C.ID_CONCE, C.NOMBRE_CONCE AS NOMBRE_CONCEPTO,
	E.ID_ESPECI, E.NOMBRE_ESPECI AS ESPECI_MOV
FROM TIPO_MOVIMIENTO T, CONCEPTO_MOVI C, ESPECI_MOV E
WHERE T.ID_TIPO_MOV = C.ID_TIPO_MOV
AND C.ID_CONCE = E.ID_CONCE
ORDER BY 1,2,3

select * from ENTRADA_SALIDA_ENCA where ID_BODEGAO = 17 AND ID_BODEGAD = 0
SELECT * FROM ESPECI_MOV WHERE ID_ESPECI = 27 TIPO_DOCTO = 7

insert into ESPECI_MOV values(55,'EXPORTACION',13)